name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-gh-pages:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - name: git commit
        run: |
          git add -f ./dist
          git config user.email "github-action@huww98.cn"
          git config user.name "GitHub Action"
          git commit -m "Build"
          git push -f origin HEAD:gh-pages
